[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "mkdir -p logs",
  "python manage.py collectstatic --no-input",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn root_app.wsgi:application"