# Generated by Django 5.2.5 on 2026-03-30 10:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the category', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the category (must be unique)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when category was created')),
                ('created_by', models.ForeignKey(help_text='User who created this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the product', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the product', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product (must be non-negative)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_quantity', models.IntegerField(help_text='Current stock quantity (must be non-negative)', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_stock_threshold', models.IntegerField(help_text='Minimum stock threshold for restock alerts', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('out_of_stock', 'Out of Stock'), ('archived', 'Archived')], default='active', help_text='Product status (automatically managed based on stock)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when product was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when product was last updated')),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('created_by', models.ForeignKey(help_text='User who created this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='products_pr_stock_q_ba97b5_idx'),
        ),
    ]
