# Generated by Django 5.2.5 on 2026-03-30 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_delete_examplemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the restock queue entry', primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when product was added to queue')),
                ('product', models.OneToOneField(help_text='Product that needs restocking', on_delete=django.db.models.deletion.CASCADE, related_name='restock_queue_entry', to='products.product')),
            ],
            options={
                'verbose_name': 'Restock Queue Entry',
                'verbose_name_plural': 'Restock Queue',
                'ordering': ['product__stock_quantity', 'added_at'],
            },
        ),
    ]
